modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Metallurgists-of-Create/Metallurgica/issues"
[[mods]]
modId="metallurgica"
version="${file.jarVersion}"
displayName="Metallurgica"
displayURL="https://github.com/Metallurgists-of-Create/Metallurgica"
logoFile="metallurgica.png"
credits="Metallurgists of Create"
authors="PouffyDev"
description='''
Replaces the vanilla ore generation with a new system that requires large processing trees to get the most out of your ore deposits.
'''
[[dependencies.metallurgica]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.metallurgica]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.metallurgica]]
modId="tfmg"
mandatory=true
versionRange="[1.0e,1.1)"
ordering="AFTER"
side="BOTH"
[[dependencies.metallurgica]]
modId="create"
mandatory=true
versionRange="[0.5.1.f,)"
ordering="NONE"
side="BOTH"