package com.freezedown.metallurgica.registry.misc;

import com.freezedown.metallurgica.Metallurgica;
import com.freezedown.metallurgica.foundation.registrate.MetallurgicaRegistrate;
import com.freezedown.metallurgica.infastructure.element.Element;
import com.freezedown.metallurgica.infastructure.element.ElementEntry;
import com.freezedown.metallurgica.registry.MetallurgicaCreativeTab;

public class MetallurgicaElements {
    private static final MetallurgicaRegistrate registrate = (MetallurgicaRegistrate) Metallurgica.registrate().setCreativeTab(MetallurgicaCreativeTab.MAIN_TAB);

    public static final ElementEntry<Element>
            NULL = createElement("null", "?"),
            HYDROGEN = createElement("hydrogen", "H"),
            HELIUM = createElement("helium", "He"),
            LITHIUM = createElement("lithium", "Li"),
            BERYLLIUM = createElement("beryllium", "Be"),
            BORON = createElement("boron", "B"),
            CARBON = createElement("carbon", "C"),
            NITROGEN = createElement("nitrogen", "N"),
            OXYGEN = createElement("oxygen", "O"),
            FLUORINE = createElement("fluorine", "F"),
            NEON = createElement("neon", "Ne"),
            SODIUM = createElement("sodium", "Na"),
            MAGNESIUM = createElement("magnesium", "Mg"),
            ALUMINUM = createElement("aluminum", "Al"),
            SILICON = createElement("silicon", "Si"),
            PHOSPHORUS = createElement("phosphorus", "P"),
            SULFUR = createElement("sulfur", "S"),
            CHLORINE = createElement("chlorine", "Cl"),
            ARGON = createElement("argon", "Ar"),
            POTASSIUM = createElement("potassium", "K"),
            CALCIUM = createElement("calcium", "Ca"),
            SCANDIUM = createElement("scandium", "Sc"),
            TITANIUM = createElement("titanium", "Ti"),
            VANADIUM = createElement("vanadium", "V"),
            CHROMIUM = createElement("chromium", "Cr"),
            MANGANESE = createElement("manganese", "Mn"),
            IRON = createElement("iron", "Fe"),
            COBALT = createElement("cobalt", "Co"),
            NICKEL = createElement("nickel", "Ni"),
            COPPER = createElement("copper", "Cu"),
            ZINC = createElement("zinc", "Zn"),
            GALLIUM = createElement("gallium", "Ga"),
            GERMANIUM = createElement("germanium", "Ge"),
            ARSENIC = createElement("arsenic", "As"),
            SELENIUM = createElement("selenium", "Se"),
            BROMINE = createElement("bromine", "Br"),
            KRYPTON = createElement("krypton", "Kr"),
            RUBIDIUM = createElement("rubidium", "Rb"),
            STRONTIUM = createElement("strontium", "Sr"),
            YTTRIUM = createElement("yttrium", "Y"),
            ZIRCONIUM = createElement("zirconium", "Zr"),
            NIOBIUM = createElement("niobium", "Nb"),
            MOLYBDENUM = createElement("molybdenum", "Mo"),
            TECHNETIUM = createElement("technetium", "Tc"),
            RUTHENIUM = createElement("ruthenium", "Ru"),
            RHODIUM = createElement("rhodium", "Rh"),
            PALLADIUM = createElement("palladium", "Pd"),
            SILVER = createElement("silver", "Ag"),
            CADMIUM = createElement("cadmium", "Cd"),
            INDIUM = createElement("indium", "In"),
            TIN = createElement("tin", "Sn"),
            ANTIMONY = createElement("antimony", "Sb"),
            TELLURIUM = createElement("tellurium", "Te"),
            IODINE = createElement("iodine", "I"),
            XENON = createElement("xenon", "Xe"),
            CESIUM = createElement("cesium", "Cs"),
            BARIUM = createElement("barium", "Ba"),
            LANTHANUM = createElement("lanthanum", "La"),
            CERIUM = createElement("cerium", "Ce"),
            PRASEODYMIUM = createElement("praseodymium", "Pr"),
            NEODYMIUM = createElement("neodymium", "Nd"),
            PROMETHIUM = createElement("promethium", "Pm"),
            SAMARIUM = createElement("samarium", "Sm"),
            EUROPIUM = createElement("europium", "Eu"),
            GADOLINIUM = createElement("gadolinium", "Gd"),
            TERBIUM = createElement("terbium", "Tb"),
            DYSPROSIUM = createElement("dysprosium", "Dy"),
            HOLMIUM = createElement("holmium", "Ho"),
            ERBIUM = createElement("erbium", "Er"),
            THULIUM = createElement("thulium", "Tm"),
            YTTERBIUM = createElement("ytterbium", "Yb"),
            LUTETIUM = createElement("lutetium", "Lu"),
            HAFNIUM = createElement("hafnium", "Hf"),
            TANTALUM = createElement("tantalum", "Ta"),
            TUNGSTEN = createElement("tungsten", "W"),
            RHENIUM = createElement("rhenium", "Re"),
            OSMIUM = createElement("osmium", "Os"),
            IRIDIUM = createElement("iridium", "Ir"),
            PLATINUM = createElement("platinum", "Pt"),
            GOLD = createElement("gold", "Au"),
            MERCURY = createElement("mercury", "Hg"),
            THALLIUM = createElement("thallium", "Tl"),
            LEAD = createElement("lead", "Pb"),
            BISMUTH = createElement("bismuth", "Bi"),
            POLONIUM = createElement("polonium", "Po"),
            ASTATINE = createElement("astatine", "At"),
            RADON = createElement("radon", "Rn"),
            FRANCIUM = createElement("francium", "Fr"),
            RADAIUM = createElement("radium", "Ra"),
            ACTINIUM = createElement("actinium", "Ac"),
            THORIUM = createElement("thorium", "Th"),
            PROTACTINIUM = createElement("protactinium", "Pa"),
            URANIUM = createElement("uranium", "U"),
            NEPTUNIUM = createElement("neptunium", "Np"),
            PLUTONIUM = createElement("plutonium", "Pu"),
            AMERICIUM = createElement("americium", "Am"),
            CURIUM = createElement("curium", "Cm"),
            BERKELIUM = createElement("berkelium", "Bk"),
            CALIFORNIUM = createElement("californium", "Cf"),
            EINSTEINIUM = createElement("einsteinium", "Es"),
            FERMIUM = createElement("fermium", "Fm"),
            MENDELEVIUM = createElement("mendelevium", "Md"),
            NOBELIUM = createElement("nobelium", "No"),
            LAWRENCIUM = createElement("lawrencium", "Lr"),
            RUTHERFORDIUM = createElement("rutherfordium", "Rf"),
            DUBNIUM = createElement("dubnium", "Db"),
            SEABORGIUM = createElement("seaborgium", "Sg"),
            BOHRIUM = createElement("bohrum", "Bh"),
            HASSIUM = createElement("hassium", "Hs"),
            MEITNERIUM = createElement("meitnerium", "Mt"),
            DARMSTADTIUM = createElement("darmstadtium", "Ds"),
            ROENTGENIUM = createElement("roentgenium", "Rg"),
            COPERNICIUM = createElement("copernicium", "Cn"),
            NIHONIUM = createElement("nihonium", "Nh"),
            FLEROVIUM = createElement("flerovium", "Fl"),
            MOSCOVIUM = createElement("moscovium", "Mc"),
            LIVERMORIUM = createElement("livermorium", "Lv"),
            TENNESSINE = createElement("tennessine", "Ts"),
            OGANESSON = createElement("oganesson", "Og"),
            NETHERIUM = createElement("netherium", "Nt");



    private static ElementEntry<Element> createElement(String name, String symbol) {
        return registrate.element(name, symbol, Element::new).register();
    }


    public static void register() {

    }
}
