name: Build
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get branch name
        id: get_branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPU
      - name: Get MC version and mod version
        uses: christian-draeger/read-properties@908f99d3334be3802ec7cb528395a69d19914e7b
        id: read_properties
        with:
          path: gradle.properties
          properties: 'mod.id mod.version'
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-includes: |
            caches
      - name: Build jar
        run: ./gradlew buildAndCollect
      - name: Find jars
        id: find_jars
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "jars<<$EOF" >> $GITHUB_OUTPUT
          find ./build/libs/ -type f -name "*.jar" ! -name "*-sources.jar" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
      - name: Send building message to discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        if: github.event_name == 'push' && env.DISCORD_WEBHOOK != ''
        uses: realRobotix/action-discord-notifier@v1.2.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message-title: Building mod from branch ${{ steps.get_branch.outputs.branch }}
      - name: Send built file to discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        if: env.DISCORD_WEBHOOK != ''
        run: |
          while IFS= read -r f
            do curl -F "file=@\"$f\";filename=\"$(echo ${f##*/} | sed 's/+/-/g')\"" $DISCORD_WEBHOOK
          done <<< "${{ steps.find_jars.outputs.jars }}"
      
